baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"
title = "Hi! I am Sartaj."
copyright = "Sartaj Singh"
readOtherPosts = "Read other posts"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Sartaj Singh"
  keywords = "homepage, blog, python, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  homesubtitle = "Python Developer. Data Wrangler"

  [params.logo]
    logoText = "Mothership"
    logoHomeLink = "/"


# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url = "http://blog.sartajsingh.dev"


#[languages]
  #[languages.en]
    #title = "Hi! I am Sartaj."
    #homesubtitle = "Python Developer. Data Wrangler"
    #keywords = ""
    #copyright = "Sartaj Singh"
    #readOtherPosts = "Read other posts"

    #[languages.en.params.logo]
      #logoText = "Mothership"
      #logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    #[languages.en.menu]
      #[[languages.en.menu.main]]
        #identifier = "about"
        #name = "About"
        #url = "/about"
      #[[languages.en.menu.main]]
        #identifier = "blog"
        #name = "Blog"
        #url = "/blog"
